udp:
  ip: "192.168.1.54"   
  port: 5000          

topics:
  - name: "/go1/cmd_vel"
    type: "geometry_msgs/Twist"
  - name: "/go1/attach"
    type: "std_msgs/Empty"
  - name: "/go1/detach"
    type: "std_msgs/Empty"
  - name: "/go1/stand"
    type: "std_msgs/Empty"
  - name: "/go1/sit"
    type: "std_msgs/Empty"